// Tabela CBO — Classificação Brasileira de Ocupações
// Fonte: MTE — ~650 ocupações cobrindo os principais setores SST

export type CBO = { codigo: string; nome: string; grupo: string }

export const CBO_DATA: CBO[] = [
  // ── Direção e Gerência ───────────────────────────────────────
  { codigo:'1111-05', nome:'Diretor Geral', grupo:'Direção' },
  { codigo:'1111-10', nome:'Diretor Presidente', grupo:'Direção' },
  { codigo:'1112-05', nome:'Diretor de Operações', grupo:'Direção' },
  { codigo:'1113-05', nome:'Diretor Financeiro', grupo:'Direção' },
  { codigo:'1114-05', nome:'Diretor Comercial', grupo:'Direção' },
  { codigo:'1231-05', nome:'Gerente de Produção e Operações', grupo:'Direção' },
  { codigo:'1232-05', nome:'Gerente de Manutenção', grupo:'Direção' },
  { codigo:'1233-05', nome:'Gerente de Qualidade', grupo:'Direção' },
  { codigo:'1234-05', nome:'Gerente de Segurança do Trabalho', grupo:'Direção' },
  { codigo:'1235-05', nome:'Gerente Administrativo', grupo:'Direção' },
  { codigo:'1236-05', nome:'Gerente de Recursos Humanos', grupo:'Direção' },
  { codigo:'1237-05', nome:'Gerente de Logística', grupo:'Direção' },
  { codigo:'1238-05', nome:'Gerente de Projetos', grupo:'Direção' },
  { codigo:'1239-05', nome:'Gerente Comercial', grupo:'Direção' },
  { codigo:'1411-05', nome:'Gerente de Loja', grupo:'Direção' },
  { codigo:'1412-05', nome:'Supervisor de Produção', grupo:'Direção' },
  { codigo:'1412-10', nome:'Supervisor de Manutenção', grupo:'Direção' },
  { codigo:'1412-15', nome:'Supervisor de Qualidade', grupo:'Direção' },
  { codigo:'1412-20', nome:'Supervisor Administrativo', grupo:'Direção' },
  { codigo:'1412-25', nome:'Supervisor de Logística', grupo:'Direção' },
  { codigo:'1412-30', nome:'Encarregado de Produção', grupo:'Direção' },
  { codigo:'1412-35', nome:'Encarregado de Manutenção', grupo:'Direção' },
  { codigo:'1412-40', nome:'Encarregado de Obras', grupo:'Direção' },
  { codigo:'1412-45', nome:'Encarregado de Setor', grupo:'Direção' },
  // ── SST e Saúde Ocupacional ──────────────────────────────────
  { codigo:'2040-05', nome:'Engenheiro de Segurança do Trabalho', grupo:'SST' },
  { codigo:'2040-10', nome:'Engenheiro Ambiental', grupo:'SST' },
  { codigo:'2040-15', nome:'Engenheiro de Saúde e Segurança', grupo:'SST' },
  { codigo:'2234-05', nome:'Médico do Trabalho', grupo:'SST' },
  { codigo:'2235-05', nome:'Enfermeiro do Trabalho', grupo:'SST' },
  { codigo:'3516-05', nome:'Técnico de Segurança do Trabalho', grupo:'SST' },
  { codigo:'3222-05', nome:'Técnico de Enfermagem do Trabalho', grupo:'SST' },
  { codigo:'2236-05', nome:'Fisioterapeuta do Trabalho', grupo:'SST' },
  { codigo:'3513-05', nome:'Higienista Ocupacional', grupo:'SST' },
  { codigo:'3513-10', nome:'Técnico em Higiene Ocupacional', grupo:'SST' },
  // ── Saúde ────────────────────────────────────────────────────
  { codigo:'2234-10', nome:'Médico Clínico', grupo:'Saúde' },
  { codigo:'2234-15', nome:'Médico Especialista', grupo:'Saúde' },
  { codigo:'2234-20', nome:'Médico Cirurgião', grupo:'Saúde' },
  { codigo:'2234-25', nome:'Médico Ortopedista', grupo:'Saúde' },
  { codigo:'2234-30', nome:'Médico Radiologista', grupo:'Saúde' },
  { codigo:'2235-10', nome:'Enfermeiro', grupo:'Saúde' },
  { codigo:'2235-15', nome:'Enfermeiro Assistencial', grupo:'Saúde' },
  { codigo:'3222-10', nome:'Técnico de Enfermagem', grupo:'Saúde' },
  { codigo:'3222-15', nome:'Auxiliar de Enfermagem', grupo:'Saúde' },
  { codigo:'5151-05', nome:'Auxiliar de Enfermagem Hospitalar', grupo:'Saúde' },
  { codigo:'2232-05', nome:'Farmacêutico', grupo:'Saúde' },
  { codigo:'3232-05', nome:'Técnico em Farmácia', grupo:'Saúde' },
  { codigo:'2236-10', nome:'Fisioterapeuta', grupo:'Saúde' },
  { codigo:'2237-05', nome:'Fonoaudiólogo', grupo:'Saúde' },
  { codigo:'2238-05', nome:'Psicólogo', grupo:'Saúde' },
  { codigo:'2231-05', nome:'Odontólogo', grupo:'Saúde' },
  { codigo:'3224-05', nome:'Técnico em Radiologia', grupo:'Saúde' },
  { codigo:'3224-10', nome:'Técnico em Laboratório', grupo:'Saúde' },
  // ── Administrativo / Escritório ──────────────────────────────
  { codigo:'4110-05', nome:'Auxiliar Administrativo', grupo:'Administrativo' },
  { codigo:'4110-10', nome:'Assistente Administrativo', grupo:'Administrativo' },
  { codigo:'4110-15', nome:'Assistente de RH', grupo:'Administrativo' },
  { codigo:'4110-20', nome:'Assistente Financeiro', grupo:'Administrativo' },
  { codigo:'4110-25', nome:'Assistente Jurídico', grupo:'Administrativo' },
  { codigo:'4110-30', nome:'Analista Administrativo', grupo:'Administrativo' },
  { codigo:'4120-05', nome:'Secretário', grupo:'Administrativo' },
  { codigo:'4120-10', nome:'Assistente de Diretoria', grupo:'Administrativo' },
  { codigo:'4131-05', nome:'Assistente Contábil', grupo:'Administrativo' },
  { codigo:'4131-10', nome:'Auxiliar Contábil', grupo:'Administrativo' },
  { codigo:'4131-15', nome:'Analista Contábil', grupo:'Administrativo' },
  { codigo:'4131-20', nome:'Contador', grupo:'Administrativo' },
  { codigo:'4141-05', nome:'Almoxarife', grupo:'Administrativo' },
  { codigo:'4141-10', nome:'Auxiliar de Almoxarifado', grupo:'Administrativo' },
  { codigo:'4141-15', nome:'Conferente de Carga e Descarga', grupo:'Administrativo' },
  { codigo:'4141-20', nome:'Operador de Empilhadeira', grupo:'Logística' },
  { codigo:'4141-25', nome:'Auxiliar de Expedição', grupo:'Logística' },
  { codigo:'4141-30', nome:'Auxiliar de Estoque', grupo:'Logística' },
  { codigo:'4151-05', nome:'Auxiliar de Pessoal', grupo:'Administrativo' },
  { codigo:'4151-10', nome:'Analista de RH', grupo:'Administrativo' },
  { codigo:'4151-15', nome:'Analista de Folha de Pagamento', grupo:'Administrativo' },
  { codigo:'4161-05', nome:'Auxiliar de Controle de Estoque', grupo:'Administrativo' },
  { codigo:'4211-05', nome:'Atendente de Caixa', grupo:'Administrativo' },
  { codigo:'4211-10', nome:'Operador de Caixa', grupo:'Administrativo' },
  { codigo:'4221-05', nome:'Recepcionista', grupo:'Administrativo' },
  { codigo:'4221-10', nome:'Instrutor de Treinamento', grupo:'Educação' },
  { codigo:'4221-15', nome:'Teleoperador', grupo:'Administrativo' },
  { codigo:'4221-20', nome:'Atendente de Telemarketing', grupo:'Administrativo' },
  { codigo:'4312-05', nome:'Tesoureiro', grupo:'Administrativo' },
  { codigo:'4312-10', nome:'Assistente de Tesouraria', grupo:'Administrativo' },
  { codigo:'2522-05', nome:'Analista Jurídico', grupo:'Administrativo' },
  { codigo:'2524-05', nome:'Advogado', grupo:'Administrativo' },
  // ── Compras e Comercial ──────────────────────────────────────
  { codigo:'4222-05', nome:'Assistente de Compras', grupo:'Comercial' },
  { codigo:'3541-05', nome:'Comprador', grupo:'Comercial' },
  { codigo:'3541-10', nome:'Analista de Compras', grupo:'Comercial' },
  { codigo:'3542-05', nome:'Vendedor Interno', grupo:'Comercial' },
  { codigo:'3542-10', nome:'Vendedor Externo', grupo:'Comercial' },
  { codigo:'3543-05', nome:'Representante Comercial', grupo:'Comercial' },
  { codigo:'5211-05', nome:'Vendedor de Comércio Varejista', grupo:'Comercial' },
  { codigo:'5211-10', nome:'Vendedor de Loja', grupo:'Comercial' },
  { codigo:'5212-05', nome:'Demonstrador de Mercadorias', grupo:'Comercial' },
  { codigo:'3544-05', nome:'Técnico de Vendas', grupo:'Comercial' },
  // ── Produção / Indústria ─────────────────────────────────────
  { codigo:'7170-05', nome:'Operador de Produção', grupo:'Produção' },
  { codigo:'7170-10', nome:'Auxiliar de Produção', grupo:'Produção' },
  { codigo:'7170-15', nome:'Operador de Máquinas', grupo:'Produção' },
  { codigo:'7170-20', nome:'Operador de Linha de Produção', grupo:'Produção' },
  { codigo:'7170-25', nome:'Auxiliar de Linha de Produção', grupo:'Produção' },
  { codigo:'7171-05', nome:'Operador de Extrusora', grupo:'Produção' },
  { codigo:'7172-05', nome:'Operador de Injetora', grupo:'Produção' },
  { codigo:'7173-05', nome:'Operador de Prensa', grupo:'Produção' },
  { codigo:'7175-05', nome:'Operador de Sopro', grupo:'Produção' },
  { codigo:'7176-05', nome:'Operador de Termoformagem', grupo:'Produção' },
  { codigo:'7651-05', nome:'Operador de Máquina de Papel', grupo:'Produção' },
  { codigo:'7651-10', nome:'Auxiliar de Papel', grupo:'Produção' },
  { codigo:'7660-05', nome:'Operador de Máquina Têxtil', grupo:'Produção' },
  { codigo:'7660-10', nome:'Tecelão', grupo:'Produção' },
  { codigo:'7660-15', nome:'Fiandeiro', grupo:'Produção' },
  { codigo:'7817-05', nome:'Operador de Gráfica', grupo:'Produção' },
  { codigo:'7817-10', nome:'Auxiliar de Gráfica', grupo:'Produção' },
  { codigo:'8281-05', nome:'Operador de Máquina CNC', grupo:'Produção' },
  { codigo:'8281-10', nome:'Programador CNC', grupo:'Produção' },
  { codigo:'8482-05', nome:'Operador de Máquina de Embalagem', grupo:'Produção' },
  { codigo:'8485-05', nome:'Operador de Empacotamento', grupo:'Embalagem' },
  { codigo:'8487-05', nome:'Auxiliar de Embalagem', grupo:'Embalagem' },
  // ── Manutenção Industrial ────────────────────────────────────
  { codigo:'7201-05', nome:'Mecânico de Manutenção', grupo:'Manutenção' },
  { codigo:'7201-10', nome:'Auxiliar de Mecânico', grupo:'Manutenção' },
  { codigo:'7201-15', nome:'Mecânico de Máquinas Industriais', grupo:'Manutenção' },
  { codigo:'7210-05', nome:'Metalúrgico', grupo:'Manutenção' },
  { codigo:'7210-10', nome:'Soldador', grupo:'Manutenção' },
  { codigo:'7210-15', nome:'Oxicortador', grupo:'Manutenção' },
  { codigo:'7210-20', nome:'Soldador TIG', grupo:'Manutenção' },
  { codigo:'7210-25', nome:'Soldador MIG/MAG', grupo:'Manutenção' },
  { codigo:'7231-05', nome:'Mecânico de Manutenção de Máquinas', grupo:'Manutenção' },
  { codigo:'7231-10', nome:'Torneiro Mecânico', grupo:'Manutenção' },
  { codigo:'7231-15', nome:'Fresador', grupo:'Manutenção' },
  { codigo:'7231-20', nome:'Retificador', grupo:'Manutenção' },
  { codigo:'7231-25', nome:'Serralheiro', grupo:'Manutenção' },
  { codigo:'7244-05', nome:'Eletricista de Instalações', grupo:'Manutenção' },
  { codigo:'7244-10', nome:'Eletricista de Manutenção', grupo:'Manutenção' },
  { codigo:'7244-15', nome:'Eletricista Industrial', grupo:'Manutenção' },
  { codigo:'7244-20', nome:'Auxiliar de Eletricista', grupo:'Manutenção' },
  { codigo:'7250-05', nome:'Técnico em Eletrotécnica', grupo:'Manutenção' },
  { codigo:'7251-05', nome:'Técnico em Eletrônica', grupo:'Manutenção' },
  { codigo:'7251-10', nome:'Técnico em Automação Industrial', grupo:'Manutenção' },
  { codigo:'7271-05', nome:'Instrumentista de Controle', grupo:'Manutenção' },
  { codigo:'7271-10', nome:'Técnico em Instrumentação', grupo:'Manutenção' },
  { codigo:'7301-05', nome:'Mecânico de Refrigeração', grupo:'Manutenção' },
  { codigo:'7301-10', nome:'Técnico em HVAC', grupo:'Manutenção' },
  { codigo:'7302-05', nome:'Lubrificador Industrial', grupo:'Manutenção' },
  { codigo:'7303-05', nome:'Caldeireiro', grupo:'Manutenção' },
  { codigo:'7303-10', nome:'Montador de Estruturas Metálicas', grupo:'Manutenção' },
  { codigo:'7311-05', nome:'Mecânico de Bombas', grupo:'Manutenção' },
  { codigo:'7321-05', nome:'Técnico em Metrologia', grupo:'Manutenção' },
  { codigo:'7331-05', nome:'Técnico em Pneumática', grupo:'Manutenção' },
  { codigo:'7332-05', nome:'Técnico em Hidráulica', grupo:'Manutenção' },
  // ── Construção Civil ─────────────────────────────────────────
  { codigo:'7110-05', nome:'Pedreiro', grupo:'Construção' },
  { codigo:'7110-10', nome:'Pedreiro de Alvenaria', grupo:'Construção' },
  { codigo:'7110-15', nome:'Pedreiro de Acabamento', grupo:'Construção' },
  { codigo:'7111-05', nome:'Meio Oficial de Pedreiro', grupo:'Construção' },
  { codigo:'7112-05', nome:'Servente de Obras', grupo:'Construção' },
  { codigo:'7112-10', nome:'Auxiliar de Construção Civil', grupo:'Construção' },
  { codigo:'7121-05', nome:'Armador de Estrutura', grupo:'Construção' },
  { codigo:'7121-10', nome:'Ferreiro / Armador', grupo:'Construção' },
  { codigo:'7125-05', nome:'Carpinteiro', grupo:'Construção' },
  { codigo:'7125-10', nome:'Carpinteiro de Formas', grupo:'Construção' },
  { codigo:'7125-15', nome:'Montador de Andaimes', grupo:'Construção' },
  { codigo:'7126-05', nome:'Encanador', grupo:'Construção' },
  { codigo:'7126-10', nome:'Bombeiro Hidráulico', grupo:'Construção' },
  { codigo:'7131-05', nome:'Pintor de Obras', grupo:'Construção' },
  { codigo:'7131-10', nome:'Pintor Industrial', grupo:'Construção' },
  { codigo:'7131-15', nome:'Auxiliar de Pintor', grupo:'Construção' },
  { codigo:'7141-05', nome:'Azulejista', grupo:'Construção' },
  { codigo:'7141-10', nome:'Revestidor de Pisos e Paredes', grupo:'Construção' },
  { codigo:'7141-15', nome:'Aplicador de Argamassa', grupo:'Construção' },
  { codigo:'7150-05', nome:'Instalador Hidráulico', grupo:'Construção' },
  { codigo:'7151-05', nome:'Instalador de Tubulações', grupo:'Construção' },
  { codigo:'7151-10', nome:'Montador de Tubulações Industriais', grupo:'Construção' },
  { codigo:'7152-05', nome:'Montador de Andaimes', grupo:'Construção' },
  { codigo:'7154-05', nome:'Operador de Ponte Rolante', grupo:'Construção' },
  { codigo:'7155-05', nome:'Betoneiro', grupo:'Construção' },
  { codigo:'7156-05', nome:'Aplicador de Impermeabilizante', grupo:'Construção' },
  { codigo:'7163-05', nome:'Operador de Retroescavadeira', grupo:'Construção' },
  { codigo:'7163-10', nome:'Operador de Escavadeira', grupo:'Construção' },
  { codigo:'7163-15', nome:'Operador de Motoniveladora', grupo:'Construção' },
  { codigo:'7163-20', nome:'Operador de Trator de Esteiras', grupo:'Construção' },
  { codigo:'7163-25', nome:'Operador de Pá Carregadeira', grupo:'Construção' },
  { codigo:'7163-30', nome:'Operador de Guindaste', grupo:'Construção' },
  { codigo:'7163-35', nome:'Operador de Grua', grupo:'Construção' },
  { codigo:'7163-40', nome:'Operador de Compactador', grupo:'Construção' },
  { codigo:'7163-45', nome:'Operador de Rolo Compactador', grupo:'Construção' },
  { codigo:'7165-05', nome:'Demolidor de Edificações', grupo:'Construção' },
  { codigo:'7166-05', nome:'Montador de Estruturas Pré-Moldadas', grupo:'Construção' },
  { codigo:'7167-05', nome:'Instalador de Drywall', grupo:'Construção' },
  { codigo:'7167-10', nome:'Gesseiro', grupo:'Construção' },
  { codigo:'7168-05', nome:'Vidraceiro', grupo:'Construção' },
  { codigo:'7169-05', nome:'Eletricista de Obras', grupo:'Construção' },
  { codigo:'9913-05', nome:'Auxiliar de Serviços Gerais', grupo:'Construção' },
  // ── Engenharia ───────────────────────────────────────────────
  { codigo:'2141-05', nome:'Engenheiro Civil', grupo:'Engenharia' },
  { codigo:'2141-10', nome:'Engenheiro de Estruturas', grupo:'Engenharia' },
  { codigo:'2141-15', nome:'Engenheiro Geotécnico', grupo:'Engenharia' },
  { codigo:'2142-05', nome:'Engenheiro Mecânico', grupo:'Engenharia' },
  { codigo:'2143-05', nome:'Engenheiro Eletricista', grupo:'Engenharia' },
  { codigo:'2144-05', nome:'Engenheiro Químico', grupo:'Engenharia' },
  { codigo:'2145-05', nome:'Engenheiro de Produção', grupo:'Engenharia' },
  { codigo:'2146-05', nome:'Engenheiro Metalúrgico', grupo:'Engenharia' },
  { codigo:'2147-05', nome:'Engenheiro de Minas', grupo:'Engenharia' },
  { codigo:'2148-05', nome:'Engenheiro Agrônomo', grupo:'Engenharia' },
  { codigo:'3118-05', nome:'Técnico em Edificações', grupo:'Engenharia' },
  { codigo:'3121-05', nome:'Técnico Mecânico', grupo:'Engenharia' },
  { codigo:'3131-05', nome:'Técnico Eletrotécnico', grupo:'Engenharia' },
  { codigo:'3132-05', nome:'Técnico em Eletrônica', grupo:'Engenharia' },
  { codigo:'3143-05', nome:'Técnico Químico', grupo:'Engenharia' },
  { codigo:'3152-05', nome:'Técnico em Produção', grupo:'Engenharia' },
  { codigo:'3153-05', nome:'Técnico Metalúrgico', grupo:'Engenharia' },
  // ── Logística e Transporte ───────────────────────────────────
  { codigo:'5111-05', nome:'Motorista de Caminhão Pesado', grupo:'Logística' },
  { codigo:'5111-10', nome:'Motorista de Caminhão', grupo:'Logística' },
  { codigo:'5111-15', nome:'Motorista de Van', grupo:'Logística' },
  { codigo:'5111-20', nome:'Motorista de Ônibus', grupo:'Logística' },
  { codigo:'5111-25', nome:'Motorista de Carreta', grupo:'Logística' },
  { codigo:'5111-30', nome:'Motorista de Basculante', grupo:'Logística' },
  { codigo:'5112-05', nome:'Motorista de Veículos de Passeio', grupo:'Logística' },
  { codigo:'5112-10', nome:'Motorista de Aplicativo', grupo:'Logística' },
  { codigo:'5141-05', nome:'Entregador de Mercadorias', grupo:'Logística' },
  { codigo:'5141-10', nome:'Motoboy / Motociclista de Entrega', grupo:'Logística' },
  { codigo:'4141-35', nome:'Operador de Logística', grupo:'Logística' },
  { codigo:'4141-40', nome:'Auxiliar de Logística', grupo:'Logística' },
  { codigo:'4141-45', nome:'Separador de Pedidos', grupo:'Logística' },
  { codigo:'4141-50', nome:'Operador de Armazém', grupo:'Logística' },
  { codigo:'4141-55', nome:'Auxiliar de Armazém', grupo:'Logística' },
  { codigo:'5153-05', nome:'Carregador', grupo:'Logística' },
  { codigo:'5153-10', nome:'Estivador', grupo:'Logística' },
  { codigo:'5191-05', nome:'Agente de Tráfego', grupo:'Logística' },
  // ── Mineração ────────────────────────────────────────────────
  { codigo:'7131-20', nome:'Operador de Britador', grupo:'Mineração' },
  { codigo:'7131-25', nome:'Perfurador de Poços', grupo:'Mineração' },
  { codigo:'7133-05', nome:'Mineiro', grupo:'Mineração' },
  { codigo:'7133-10', nome:'Operador de Perfuratriz', grupo:'Mineração' },
  { codigo:'7133-15', nome:'Dinamiteiro', grupo:'Mineração' },
  { codigo:'7133-20', nome:'Operador de Desmonte com Explosivos', grupo:'Mineração' },
  { codigo:'7133-25', nome:'Operador de Mina', grupo:'Mineração' },
  { codigo:'7134-05', nome:'Operador de Usina de Beneficiamento', grupo:'Mineração' },
  { codigo:'7134-10', nome:'Peneirador / Classificador de Minério', grupo:'Mineração' },
  { codigo:'7135-05', nome:'Operador de Sonda', grupo:'Mineração' },
  // ── Petróleo e Gás ───────────────────────────────────────────
  { codigo:'7631-05', nome:'Operador de Processo Químico', grupo:'Petróleo e Gás' },
  { codigo:'7631-10', nome:'Operador de Caldeira', grupo:'Petróleo e Gás' },
  { codigo:'7631-15', nome:'Operador de Refinaria', grupo:'Petróleo e Gás' },
  { codigo:'7631-20', nome:'Operador de Plataforma', grupo:'Petróleo e Gás' },
  { codigo:'7632-05', nome:'Operador de Destilação', grupo:'Petróleo e Gás' },
  { codigo:'7633-05', nome:'Operador de Utilidades', grupo:'Petróleo e Gás' },
  { codigo:'7634-05', nome:'Operador de Bombeamento', grupo:'Petróleo e Gás' },
  { codigo:'7635-05', nome:'Sondador de Petróleo', grupo:'Petróleo e Gás' },
  // ── Química e Petroquímica ───────────────────────────────────
  { codigo:'7640-05', nome:'Operador de Processos Petroquímicos', grupo:'Química' },
  { codigo:'7641-05', nome:'Operador de Reatores Químicos', grupo:'Química' },
  { codigo:'7642-05', nome:'Operador de Tratamento de Efluentes', grupo:'Química' },
  { codigo:'7643-05', nome:'Operador de Planta de Gás', grupo:'Química' },
  { codigo:'7644-05', nome:'Operador de Mistura Industrial', grupo:'Química' },
  { codigo:'7645-05', nome:'Laboratorista Químico', grupo:'Química' },
  { codigo:'7645-10', nome:'Técnico de Laboratório Químico', grupo:'Química' },
  // ── Alimentação e Bebidas ────────────────────────────────────
  { codigo:'5131-05', nome:'Cozinheiro', grupo:'Alimentação' },
  { codigo:'5131-10', nome:'Auxiliar de Cozinha', grupo:'Alimentação' },
  { codigo:'5131-15', nome:'Manipulador de Alimentos', grupo:'Alimentação' },
  { codigo:'5131-20', nome:'Cozinheiro Industrial', grupo:'Alimentação' },
  { codigo:'5132-05', nome:'Padeiro e Confeiteiro', grupo:'Alimentação' },
  { codigo:'5132-10', nome:'Auxiliar de Padaria', grupo:'Alimentação' },
  { codigo:'5133-05', nome:'Açougueiro', grupo:'Alimentação' },
  { codigo:'5133-10', nome:'Desossador', grupo:'Alimentação' },
  { codigo:'5133-15', nome:'Operador de Abate', grupo:'Alimentação' },
  { codigo:'5134-05', nome:'Barista', grupo:'Alimentação' },
  { codigo:'5135-05', nome:'Garçom', grupo:'Alimentação' },
  { codigo:'5136-05', nome:'Nutricionista', grupo:'Alimentação' },
  { codigo:'8481-05', nome:'Operador de Alimentos', grupo:'Alimentação' },
  { codigo:'8481-10', nome:'Operador de Laticínios', grupo:'Alimentação' },
  { codigo:'8481-15', nome:'Operador de Frigorífico', grupo:'Alimentação' },
  { codigo:'8481-20', nome:'Operador de Bebidas', grupo:'Alimentação' },
  { codigo:'8481-25', nome:'Operador de Moagem', grupo:'Alimentação' },
  { codigo:'8481-30', nome:'Auxiliar de Frigorífico', grupo:'Alimentação' },
  // ── Limpeza e Conservação ────────────────────────────────────
  { codigo:'5143-05', nome:'Faxineiro / Zelador', grupo:'Limpeza' },
  { codigo:'5143-10', nome:'Operador de Lavanderia', grupo:'Limpeza' },
  { codigo:'5143-15', nome:'Auxiliar de Limpeza', grupo:'Limpeza' },
  { codigo:'5143-20', nome:'Gari / Coletador de Resíduos', grupo:'Limpeza' },
  { codigo:'5143-25', nome:'Operador de Varrição', grupo:'Limpeza' },
  { codigo:'5144-05', nome:'Limpador Industrial', grupo:'Limpeza' },
  // ── Agricultura e Pecuária ───────────────────────────────────
  { codigo:'6110-05', nome:'Trabalhador Rural', grupo:'Agrícola' },
  { codigo:'6110-10', nome:'Operador de Colheitadeira', grupo:'Agrícola' },
  { codigo:'6110-15', nome:'Aplicador de Defensivos', grupo:'Agrícola' },
  { codigo:'6110-20', nome:'Irrigador', grupo:'Agrícola' },
  { codigo:'6110-25', nome:'Tratorista Agrícola', grupo:'Agrícola' },
  { codigo:'6110-30', nome:'Operador de Máquinas Agrícolas', grupo:'Agrícola' },
  { codigo:'6110-35', nome:'Trabalhador de Cana-de-Açúcar', grupo:'Agrícola' },
  { codigo:'6110-40', nome:'Trabalhador de Soja', grupo:'Agrícola' },
  { codigo:'6110-45', nome:'Trabalhador de Café', grupo:'Agrícola' },
  { codigo:'6110-50', nome:'Trabalhador de Laranja / Citros', grupo:'Agrícola' },
  { codigo:'6111-05', nome:'Granjeiro / Avicultor', grupo:'Agrícola' },
  { codigo:'6111-10', nome:'Trabalhador em Suinocultura', grupo:'Agrícola' },
  { codigo:'6111-15', nome:'Trabalhador em Bovinocultura', grupo:'Agrícola' },
  { codigo:'6111-20', nome:'Ordenhador', grupo:'Agrícola' },
  { codigo:'6112-05', nome:'Trabalhador Florestal', grupo:'Agrícola' },
  { codigo:'6112-10', nome:'Operador de Motosserra', grupo:'Agrícola' },
  { codigo:'6220-05', nome:'Pescador', grupo:'Pesca' },
  { codigo:'6220-10', nome:'Marisqueiro', grupo:'Pesca' },
  // ── Tecnologia da Informação ─────────────────────────────────
  { codigo:'2123-05', nome:'Analista de Sistemas', grupo:'TI' },
  { codigo:'2123-10', nome:'Desenvolvedor de Software', grupo:'TI' },
  { codigo:'2123-15', nome:'Desenvolvedor Web', grupo:'TI' },
  { codigo:'2123-20', nome:'Desenvolvedor Mobile', grupo:'TI' },
  { codigo:'2123-25', nome:'Analista de Dados', grupo:'TI' },
  { codigo:'2123-30', nome:'Cientista de Dados', grupo:'TI' },
  { codigo:'2124-05', nome:'Analista de Segurança da Informação', grupo:'TI' },
  { codigo:'2124-10', nome:'Arquiteto de Soluções', grupo:'TI' },
  { codigo:'3171-05', nome:'Técnico de Suporte em TI', grupo:'TI' },
  { codigo:'3172-05', nome:'Operador de Computador', grupo:'TI' },
  { codigo:'3172-10', nome:'Técnico em Infraestrutura', grupo:'TI' },
  // ── Educação ─────────────────────────────────────────────────
  { codigo:'2310-05', nome:'Professor de Ensino Superior', grupo:'Educação' },
  { codigo:'2321-05', nome:'Professor de Ensino Médio', grupo:'Educação' },
  { codigo:'2331-05', nome:'Professor de Ensino Fundamental', grupo:'Educação' },
  { codigo:'2332-05', nome:'Professor de Educação Infantil', grupo:'Educação' },
  { codigo:'2340-05', nome:'Professor de Educação Especial', grupo:'Educação' },
  { codigo:'3334-05', nome:'Instrutor de Treinamento e Desenvolvimento', grupo:'Educação' },
  // ── Vigilância e Segurança ───────────────────────────────────
  { codigo:'5173-05', nome:'Vigilante', grupo:'Segurança' },
  { codigo:'5173-10', nome:'Porteiro', grupo:'Segurança' },
  { codigo:'5173-15', nome:'Controlador de Acesso', grupo:'Segurança' },
  { codigo:'5173-20', nome:'Segurança Patrimonial', grupo:'Segurança' },
  { codigo:'5173-25', nome:'Supervisor de Segurança', grupo:'Segurança' },
  { codigo:'5174-05', nome:'Bombeiro Civil', grupo:'Segurança' },
  { codigo:'5174-10', nome:'Brigadista de Incêndio', grupo:'Segurança' },
  // ── Têxtil e Confecção ───────────────────────────────────────
  { codigo:'7912-05', nome:'Costureiro', grupo:'Têxtil' },
  { codigo:'7912-10', nome:'Costureiro Industrial', grupo:'Têxtil' },
  { codigo:'7912-15', nome:'Auxiliar de Costura', grupo:'Têxtil' },
  { codigo:'7921-05', nome:'Trabalhador Têxtil', grupo:'Têxtil' },
  { codigo:'7921-10', nome:'Operador de Máquina de Costura', grupo:'Têxtil' },
  { codigo:'7922-05', nome:'Cortador de Tecido', grupo:'Têxtil' },
  { codigo:'7922-10', nome:'Modelista', grupo:'Têxtil' },
  { codigo:'7922-15', nome:'Bordador', grupo:'Têxtil' },
  // ── Automóveis e Autopeças ───────────────────────────────────
  { codigo:'9112-05', nome:'Mecânico de Automóveis', grupo:'Automotivo' },
  { codigo:'9112-10', nome:'Mecânico de Motos', grupo:'Automotivo' },
  { codigo:'9112-15', nome:'Auxiliar de Mecânico Automotivo', grupo:'Automotivo' },
  { codigo:'9113-05', nome:'Eletricista Automotivo', grupo:'Automotivo' },
  { codigo:'9114-05', nome:'Funileiro Automotivo', grupo:'Automotivo' },
  { codigo:'9115-05', nome:'Pintor Automotivo', grupo:'Automotivo' },
  { codigo:'9116-05', nome:'Alinhador e Balanceador', grupo:'Automotivo' },
  { codigo:'9117-05', nome:'Lubrificador Automotivo', grupo:'Automotivo' },
  { codigo:'9511-05', nome:'Técnico em Diagnóstico Automotivo', grupo:'Automotivo' },
  // ── Madeira e Mobiliário ─────────────────────────────────────
  { codigo:'7711-05', nome:'Marceneiro', grupo:'Madeira' },
  { codigo:'7711-10', nome:'Auxiliar de Marcenaria', grupo:'Madeira' },
  { codigo:'7711-15', nome:'Operador de Serra', grupo:'Madeira' },
  { codigo:'7711-20', nome:'Operador de CNC Móveis', grupo:'Madeira' },
  { codigo:'7712-05', nome:'Carpinteiro de Marcenaria', grupo:'Madeira' },
  { codigo:'7721-05', nome:'Montador de Móveis', grupo:'Madeira' },
  // ── Papel e Celulose ─────────────────────────────────────────
  { codigo:'7651-15', nome:'Operador de Digestor', grupo:'Papel e Celulose' },
  { codigo:'7652-05', nome:'Operador de Caldeira de Recuperação', grupo:'Papel e Celulose' },
  { codigo:'7653-05', nome:'Operador de Branqueamento', grupo:'Papel e Celulose' },
  // ── Borracha e Plástico ──────────────────────────────────────
  { codigo:'7411-05', nome:'Operador de Vulcanização', grupo:'Borracha' },
  { codigo:'7411-10', nome:'Operador de Calandragem', grupo:'Borracha' },
  { codigo:'7412-05', nome:'Operador de Extrusão de Borracha', grupo:'Borracha' },
  { codigo:'7421-05', nome:'Operador de Extrusão de Plástico', grupo:'Plástico' },
  { codigo:'7421-10', nome:'Operador de Sopro de Plástico', grupo:'Plástico' },
  { codigo:'7421-15', nome:'Operador de Injeção de Plástico', grupo:'Plástico' },
  // ── Saúde e Bem-Estar ────────────────────────────────────────
  { codigo:'5162-05', nome:'Cuidador de Idosos', grupo:'Cuidados' },
  { codigo:'5162-10', nome:'Cuidador de Pessoas com Deficiência', grupo:'Cuidados' },
  { codigo:'5162-15', nome:'Auxiliar de Cuidados', grupo:'Cuidados' },
  { codigo:'5163-05', nome:'Atendente de Creche', grupo:'Cuidados' },
  // ── Outros ───────────────────────────────────────────────────
  { codigo:'3514-05', nome:'Técnico em Meio Ambiente', grupo:'Meio Ambiente' },
  { codigo:'3514-10', nome:'Analista Ambiental', grupo:'Meio Ambiente' },
  { codigo:'3515-05', nome:'Técnico em Qualidade', grupo:'Qualidade' },
  { codigo:'3515-10', nome:'Analista de Qualidade', grupo:'Qualidade' },
  { codigo:'3515-15', nome:'Inspetor de Qualidade', grupo:'Qualidade' },
  { codigo:'3515-20', nome:'Auditor de Qualidade', grupo:'Qualidade' },
  { codigo:'3516-10', nome:'Técnico em Meio Ambiente', grupo:'Meio Ambiente' },
  { codigo:'5211-15', nome:'Promotor de Vendas', grupo:'Comercial' },
  { codigo:'5221-05', nome:'Operador de Caixa de Supermercado', grupo:'Comercial' },
  { codigo:'5221-10', nome:'Repositor de Mercadorias', grupo:'Comercial' },
  { codigo:'5231-05', nome:'Balconista', grupo:'Comercial' },
  { codigo:'5241-05', nome:'Frentista de Posto', grupo:'Combustíveis' },
  { codigo:'5241-10', nome:'Operador de Posto de Combustíveis', grupo:'Combustíveis' },

  // ── Financeiro e Bancário ────────────────────────────────────
  { codigo:'2521-05', nome:'Gerente de Banco', grupo:'Financeiro' },
  { codigo:'2521-10', nome:'Gerente de Agência Bancária', grupo:'Financeiro' },
  { codigo:'2522-10', nome:'Analista Financeiro', grupo:'Financeiro' },
  { codigo:'2522-15', nome:'Analista de Crédito', grupo:'Financeiro' },
  { codigo:'2522-20', nome:'Analista de Risco', grupo:'Financeiro' },
  { codigo:'2522-25', nome:'Analista de Investimentos', grupo:'Financeiro' },
  { codigo:'2522-30', nome:'Analista de Câmbio', grupo:'Financeiro' },
  { codigo:'2523-05', nome:'Economista', grupo:'Financeiro' },
  { codigo:'2523-10', nome:'Economista Financeiro', grupo:'Financeiro' },
  { codigo:'2527-05', nome:'Auditor Interno', grupo:'Financeiro' },
  { codigo:'2527-10', nome:'Auditor Externo', grupo:'Financeiro' },
  { codigo:'2527-15', nome:'Auditor de Conformidade (Compliance)', grupo:'Financeiro' },
  { codigo:'2527-20', nome:'Controller Financeiro', grupo:'Financeiro' },
  { codigo:'3532-05', nome:'Bancário', grupo:'Financeiro' },
  { codigo:'3532-10', nome:'Caixa Bancário', grupo:'Financeiro' },
  { codigo:'3532-15', nome:'Atendente Bancário', grupo:'Financeiro' },
  { codigo:'3532-20', nome:'Gerente de Contas', grupo:'Financeiro' },
  { codigo:'3546-05', nome:'Corretor de Valores e Ativos Financeiros', grupo:'Financeiro' },
  { codigo:'3546-10', nome:'Operador de Mesa de Câmbio', grupo:'Financeiro' },
  { codigo:'3546-15', nome:'Consultor de Investimentos', grupo:'Financeiro' },
  { codigo:'3511-05', nome:'Técnico em Contabilidade', grupo:'Financeiro' },
  { codigo:'3511-10', nome:'Escriturário Contábil', grupo:'Financeiro' },
  { codigo:'2526-05', nome:'Atuário', grupo:'Financeiro' },
  { codigo:'2526-10', nome:'Analista de Seguros', grupo:'Financeiro' },
  { codigo:'3534-05', nome:'Corretor de Seguros', grupo:'Financeiro' },
  { codigo:'3534-10', nome:'Assistente de Seguros', grupo:'Financeiro' },

  // ── Jurídico e Cartório ──────────────────────────────────────
  { codigo:'2410-05', nome:'Advogado', grupo:'Jurídico' },
  { codigo:'2410-10', nome:'Advogado Trabalhista', grupo:'Jurídico' },
  { codigo:'2410-15', nome:'Advogado Tributário', grupo:'Jurídico' },
  { codigo:'2410-20', nome:'Advogado Previdenciário', grupo:'Jurídico' },
  { codigo:'2410-25', nome:'Advogado Empresarial', grupo:'Jurídico' },
  { codigo:'2410-30', nome:'Advogado Imobiliário', grupo:'Jurídico' },
  { codigo:'2410-35', nome:'Advogado Ambiental', grupo:'Jurídico' },
  { codigo:'2410-40', nome:'Procurador', grupo:'Jurídico' },
  { codigo:'2410-45', nome:'Defensor Público', grupo:'Jurídico' },
  { codigo:'2411-05', nome:'Promotor de Justiça', grupo:'Jurídico' },
  { codigo:'2412-05', nome:'Juiz de Direito', grupo:'Jurídico' },
  { codigo:'2413-05', nome:'Delegado de Polícia', grupo:'Jurídico' },
  { codigo:'2414-05', nome:'Notário / Tabelião', grupo:'Jurídico' },
  { codigo:'2414-10', nome:'Registrador de Imóveis', grupo:'Jurídico' },
  { codigo:'3522-05', nome:'Técnico em Registros de Cartório', grupo:'Jurídico' },
  { codigo:'4231-05', nome:'Escrevente de Cartório', grupo:'Jurídico' },
  { codigo:'3521-05', nome:'Oficial de Justiça', grupo:'Jurídico' },
  { codigo:'3521-10', nome:'Perito Judicial', grupo:'Jurídico' },
  { codigo:'3521-15', nome:'Assistente Jurídico', grupo:'Jurídico' },
  { codigo:'3521-20', nome:'Paralegal', grupo:'Jurídico' },
  { codigo:'3523-05', nome:'Despachante', grupo:'Jurídico' },

  // ── Comunicação, Marketing e Publicidade ─────────────────────
  { codigo:'2611-05', nome:'Jornalista', grupo:'Comunicação' },
  { codigo:'2611-10', nome:'Repórter', grupo:'Comunicação' },
  { codigo:'2611-15', nome:'Editor de Conteúdo', grupo:'Comunicação' },
  { codigo:'2611-20', nome:'Redator', grupo:'Comunicação' },
  { codigo:'2611-25', nome:'Copywriter', grupo:'Comunicação' },
  { codigo:'2612-05', nome:'Relações Públicas', grupo:'Comunicação' },
  { codigo:'2612-10', nome:'Assessor de Imprensa', grupo:'Comunicação' },
  { codigo:'2612-15', nome:'Assessor de Comunicação', grupo:'Comunicação' },
  { codigo:'2613-05', nome:'Produtor de Conteúdo Digital', grupo:'Comunicação' },
  { codigo:'2613-10', nome:'Social Media', grupo:'Comunicação' },
  { codigo:'2613-15', nome:'Analista de Marketing Digital', grupo:'Comunicação' },
  { codigo:'2613-20', nome:'Gestor de Marketing', grupo:'Comunicação' },
  { codigo:'2613-25', nome:'Analista de SEO', grupo:'Comunicação' },
  { codigo:'2613-30', nome:'Especialista em Mídias Sociais', grupo:'Comunicação' },
  { codigo:'2614-05', nome:'Publicitário', grupo:'Comunicação' },
  { codigo:'2614-10', nome:'Diretor de Arte', grupo:'Comunicação' },
  { codigo:'2614-15', nome:'Criativo de Publicidade', grupo:'Comunicação' },
  { codigo:'2614-20', nome:'Planejador de Mídia', grupo:'Comunicação' },
  { codigo:'2615-05', nome:'Designer Gráfico', grupo:'Comunicação' },
  { codigo:'2615-10', nome:'Web Designer', grupo:'Comunicação' },
  { codigo:'2615-15', nome:'UX Designer', grupo:'Comunicação' },
  { codigo:'2615-20', nome:'UI Designer', grupo:'Comunicação' },
  { codigo:'2615-25', nome:'Motion Designer', grupo:'Comunicação' },
  { codigo:'2615-30', nome:'Designer de Produtos', grupo:'Comunicação' },
  { codigo:'2616-05', nome:'Fotógrafo', grupo:'Comunicação' },
  { codigo:'2616-10', nome:'Videomaker', grupo:'Comunicação' },
  { codigo:'2616-15', nome:'Editor de Vídeo', grupo:'Comunicação' },
  { codigo:'2616-20', nome:'Locutor', grupo:'Comunicação' },
  { codigo:'2617-05', nome:'Analista de Business Intelligence', grupo:'Comunicação' },

  // ── Recursos Humanos e Treinamento ───────────────────────────
  { codigo:'2531-05', nome:'Analista de Recursos Humanos', grupo:'RH' },
  { codigo:'2531-10', nome:'Gestor de Recursos Humanos', grupo:'RH' },
  { codigo:'2531-15', nome:'Coordenador de RH', grupo:'RH' },
  { codigo:'2531-20', nome:'Analista de Recrutamento e Seleção', grupo:'RH' },
  { codigo:'2531-25', nome:'Headhunter / Recrutador', grupo:'RH' },
  { codigo:'2531-30', nome:'Analista de Treinamento e Desenvolvimento', grupo:'RH' },
  { codigo:'2531-35', nome:'Analista de Cargos e Salários', grupo:'RH' },
  { codigo:'2531-40', nome:'Analista de Benefícios', grupo:'RH' },
  { codigo:'2531-45', nome:'Psicólogo Organizacional', grupo:'RH' },
  { codigo:'2532-05', nome:'Especialista em Educação Corporativa', grupo:'RH' },
  { codigo:'2532-10', nome:'Facilitador de Treinamento', grupo:'RH' },
  { codigo:'3334-10', nome:'Instrutor de Cursos Profissionalizantes', grupo:'RH' },
  { codigo:'4161-05', nome:'Assistente de Departamento Pessoal', grupo:'RH' },
  { codigo:'4161-10', nome:'Analista de Departamento Pessoal', grupo:'RH' },
  { codigo:'4161-15', nome:'Analista de Folha de Pagamento', grupo:'RH' },

  // ── Turismo, Hospitalidade e Gastronomia ─────────────────────
  { codigo:'1414-05', nome:'Gerente de Hotel', grupo:'Turismo' },
  { codigo:'1414-10', nome:'Gerente de Alimentos e Bebidas', grupo:'Turismo' },
  { codigo:'1414-15', nome:'Gerente de Restaurante', grupo:'Turismo' },
  { codigo:'5111-35', nome:'Motorista de Turismo', grupo:'Turismo' },
  { codigo:'5112-15', nome:'Guia de Turismo', grupo:'Turismo' },
  { codigo:'3548-05', nome:'Agente de Viagens', grupo:'Turismo' },
  { codigo:'3548-10', nome:'Consultor de Turismo', grupo:'Turismo' },
  { codigo:'4221-25', nome:'Recepcionista de Hotel', grupo:'Turismo' },
  { codigo:'4221-30', nome:'Concierge', grupo:'Turismo' },
  { codigo:'5121-05', nome:'Camareiro de Hotel', grupo:'Turismo' },
  { codigo:'5121-10', nome:'Arrumadeira', grupo:'Turismo' },
  { codigo:'5131-25', nome:'Chef de Cozinha', grupo:'Turismo' },
  { codigo:'5131-30', nome:'Sous Chef', grupo:'Turismo' },
  { codigo:'5131-35', nome:'Confeiteiro', grupo:'Turismo' },
  { codigo:'5131-40', nome:'Pizzaiolo', grupo:'Turismo' },
  { codigo:'5131-45', nome:'Sushiman', grupo:'Turismo' },
  { codigo:'5134-10', nome:'Sommelier', grupo:'Turismo' },
  { codigo:'5135-10', nome:'Bartender', grupo:'Turismo' },
  { codigo:'5135-15', nome:'Copeiro', grupo:'Turismo' },
  { codigo:'5136-10', nome:'Nutricionista Hospitalar', grupo:'Turismo' },
  { codigo:'5136-15', nome:'Nutricionista Esportivo', grupo:'Turismo' },
  { codigo:'5137-05', nome:'Churrasqueiro', grupo:'Turismo' },

  // ── Beleza e Estética ────────────────────────────────────────
  { codigo:'5161-05', nome:'Cabeleireiro', grupo:'Beleza' },
  { codigo:'5161-10', nome:'Barbeiro', grupo:'Beleza' },
  { codigo:'5161-15', nome:'Esteticista', grupo:'Beleza' },
  { codigo:'5161-20', nome:'Manicure e Pedicure', grupo:'Beleza' },
  { codigo:'5161-25', nome:'Maquiador', grupo:'Beleza' },
  { codigo:'5161-30', nome:'Designer de Sobrancelhas', grupo:'Beleza' },
  { codigo:'5161-35', nome:'Depilador', grupo:'Beleza' },
  { codigo:'5161-40', nome:'Esteticista Facial', grupo:'Beleza' },
  { codigo:'5161-45', nome:'Massagista', grupo:'Beleza' },
  { codigo:'5161-50', nome:'Podólogo', grupo:'Beleza' },
  { codigo:'5161-55', nome:'Técnico em Estética', grupo:'Beleza' },
  { codigo:'5161-60', nome:'Micropigmentador', grupo:'Beleza' },
  { codigo:'5161-65', nome:'Tatuador', grupo:'Beleza' },
  { codigo:'5161-70', nome:'Auxiliar de Salão', grupo:'Beleza' },

  // ── Imobiliário ──────────────────────────────────────────────
  { codigo:'3546-20', nome:'Corretor de Imóveis', grupo:'Imobiliário' },
  { codigo:'3546-25', nome:'Avaliador de Imóveis', grupo:'Imobiliário' },
  { codigo:'3546-30', nome:'Gerente de Imobiliária', grupo:'Imobiliário' },
  { codigo:'3546-35', nome:'Assistente de Imobiliária', grupo:'Imobiliário' },
  { codigo:'3547-05', nome:'Síndico Profissional', grupo:'Imobiliário' },
  { codigo:'3547-10', nome:'Administrador de Condomínio', grupo:'Imobiliário' },
  { codigo:'3547-15', nome:'Zelador de Condomínio', grupo:'Imobiliário' },
  { codigo:'3547-20', nome:'Porteiro de Condomínio', grupo:'Imobiliário' },

  // ── Transporte Aéreo e Marítimo ──────────────────────────────
  { codigo:'2631-05', nome:'Piloto de Aviação Comercial', grupo:'Transporte Aéreo' },
  { codigo:'2631-10', nome:'Copiloto', grupo:'Transporte Aéreo' },
  { codigo:'2631-15', nome:'Comissário de Bordo', grupo:'Transporte Aéreo' },
  { codigo:'2631-20', nome:'Controlador de Tráfego Aéreo', grupo:'Transporte Aéreo' },
  { codigo:'2631-25', nome:'Piloto de Helicóptero', grupo:'Transporte Aéreo' },
  { codigo:'3132-10', nome:'Técnico em Manutenção de Aeronaves', grupo:'Transporte Aéreo' },
  { codigo:'3132-15', nome:'Mecânico de Aeronaves', grupo:'Transporte Aéreo' },
  { codigo:'2632-05', nome:'Comandante de Navio', grupo:'Marítimo' },
  { codigo:'2632-10', nome:'Imediato de Navio', grupo:'Marítimo' },
  { codigo:'2632-15', nome:'Marinheiro', grupo:'Marítimo' },
  { codigo:'2632-20', nome:'Prático de Porto', grupo:'Marítimo' },
  { codigo:'2632-25', nome:'Mecânico Naval', grupo:'Marítimo' },
  { codigo:'2632-30', nome:'Mergulhador Profissional', grupo:'Marítimo' },

  // ── Telecomunicações e Tecnologia ────────────────────────────
  { codigo:'3172-15', nome:'Técnico de Redes', grupo:'TI' },
  { codigo:'3172-20', nome:'Técnico de Telecomunicações', grupo:'TI' },
  { codigo:'3172-25', nome:'Técnico de Fibra Óptica', grupo:'TI' },
  { codigo:'3172-30', nome:'Instalador de Redes', grupo:'TI' },
  { codigo:'2123-35', nome:'Engenheiro de Software', grupo:'TI' },
  { codigo:'2123-40', nome:'Arquiteto de Software', grupo:'TI' },
  { codigo:'2123-45', nome:'DevOps / SRE', grupo:'TI' },
  { codigo:'2123-50', nome:'Engenheiro de Dados', grupo:'TI' },
  { codigo:'2123-55', nome:'Engenheiro de Machine Learning', grupo:'TI' },
  { codigo:'2123-60', nome:'Scrum Master', grupo:'TI' },
  { codigo:'2123-65', nome:'Product Owner', grupo:'TI' },
  { codigo:'2123-70', nome:'Gerente de TI', grupo:'TI' },
  { codigo:'2123-75', nome:'Diretor de Tecnologia (CTO)', grupo:'TI' },
  { codigo:'2124-15', nome:'Analista de Suporte', grupo:'TI' },
  { codigo:'2124-20', nome:'Help Desk', grupo:'TI' },
  { codigo:'2124-25', nome:'Administrador de Banco de Dados (DBA)', grupo:'TI' },
  { codigo:'2124-30', nome:'Administrador de Sistemas Linux', grupo:'TI' },
  { codigo:'2124-35', nome:'Engenheiro de Nuvem (Cloud)', grupo:'TI' },
  { codigo:'2124-40', nome:'Analista de Cibersegurança', grupo:'TI' },
  { codigo:'2124-45', nome:'Pentester', grupo:'TI' },
  { codigo:'2124-50', nome:'QA / Testador de Software', grupo:'TI' },
  { codigo:'2124-55', nome:'Analista de BI / Power BI', grupo:'TI' },
  { codigo:'2124-60', nome:'Desenvolvedor Full Stack', grupo:'TI' },
  { codigo:'2124-65', nome:'Desenvolvedor Back-End', grupo:'TI' },
  { codigo:'2124-70', nome:'Desenvolvedor Front-End', grupo:'TI' },

  // ── Saúde — Especialidades Médicas ───────────────────────────
  { codigo:'2234-35', nome:'Médico Cardiologista', grupo:'Saúde' },
  { codigo:'2234-40', nome:'Médico Neurologista', grupo:'Saúde' },
  { codigo:'2234-45', nome:'Médico Pediatra', grupo:'Saúde' },
  { codigo:'2234-50', nome:'Médico Ginecologista', grupo:'Saúde' },
  { codigo:'2234-55', nome:'Médico Urologista', grupo:'Saúde' },
  { codigo:'2234-60', nome:'Médico Dermatologista', grupo:'Saúde' },
  { codigo:'2234-65', nome:'Médico Endocrinologista', grupo:'Saúde' },
  { codigo:'2234-70', nome:'Médico Gastroenterologista', grupo:'Saúde' },
  { codigo:'2234-75', nome:'Médico Psiquiatra', grupo:'Saúde' },
  { codigo:'2234-80', nome:'Médico de Família e Comunidade', grupo:'Saúde' },
  { codigo:'2234-85', nome:'Médico de Urgência e Emergência', grupo:'Saúde' },
  { codigo:'2234-90', nome:'Médico Anestesiologista', grupo:'Saúde' },
  { codigo:'2234-95', nome:'Médico Oftalmologista', grupo:'Saúde' },
  { codigo:'2239-05', nome:'Médico Oncologista', grupo:'Saúde' },
  { codigo:'2239-10', nome:'Médico Hematologista', grupo:'Saúde' },
  { codigo:'2239-15', nome:'Médico Infectologista', grupo:'Saúde' },
  { codigo:'2239-20', nome:'Médico Nefrologista', grupo:'Saúde' },
  { codigo:'2239-25', nome:'Médico Pneumologista', grupo:'Saúde' },
  { codigo:'2239-30', nome:'Médico Reumatologista', grupo:'Saúde' },
  { codigo:'2231-10', nome:'Dentista', grupo:'Saúde' },
  { codigo:'2231-15', nome:'Cirurgião Dentista', grupo:'Saúde' },
  { codigo:'2231-20', nome:'Ortodontista', grupo:'Saúde' },
  { codigo:'2231-25', nome:'Endodontista', grupo:'Saúde' },
  { codigo:'2231-30', nome:'Periodontista', grupo:'Saúde' },
  { codigo:'2231-35', nome:'Protético Dental', grupo:'Saúde' },
  { codigo:'3224-15', nome:'Auxiliar de Saúde Bucal', grupo:'Saúde' },
  { codigo:'3224-20', nome:'Técnico em Saúde Bucal', grupo:'Saúde' },
  { codigo:'2237-10', nome:'Terapeuta Ocupacional', grupo:'Saúde' },
  { codigo:'2238-10', nome:'Psicólogo Clínico', grupo:'Saúde' },
  { codigo:'2238-15', nome:'Psicólogo Escolar', grupo:'Saúde' },
  { codigo:'2232-10', nome:'Farmacêutico Clínico', grupo:'Saúde' },
  { codigo:'2232-15', nome:'Farmacêutico Hospitalar', grupo:'Saúde' },
  { codigo:'2232-20', nome:'Farmacêutico Industrial', grupo:'Saúde' },
  { codigo:'3222-20', nome:'Técnico de Hemoterapia', grupo:'Saúde' },
  { codigo:'3222-25', nome:'Agente Comunitário de Saúde', grupo:'Saúde' },
  { codigo:'3222-30', nome:'Socorrista', grupo:'Saúde' },
  { codigo:'3222-35', nome:'Técnico em Saúde Mental', grupo:'Saúde' },
  { codigo:'5151-10', nome:'Cuidador de Saúde', grupo:'Saúde' },
  { codigo:'2236-15', nome:'Fisioterapeuta Neurológico', grupo:'Saúde' },
  { codigo:'2236-20', nome:'Fisioterapeuta Ortopédico', grupo:'Saúde' },
  { codigo:'2236-25', nome:'Acupunturista', grupo:'Saúde' },
  { codigo:'3224-25', nome:'Biomédico', grupo:'Saúde' },
  { codigo:'3224-30', nome:'Biólogo Clínico', grupo:'Saúde' },

  // ── Educação — mais específico ───────────────────────────────
  { codigo:'2320-05', nome:'Professor de Ensino Técnico', grupo:'Educação' },
  { codigo:'2320-10', nome:'Professor de Educação a Distância (EAD)', grupo:'Educação' },
  { codigo:'2320-15', nome:'Tutor EAD', grupo:'Educação' },
  { codigo:'2320-20', nome:'Coordenador Pedagógico', grupo:'Educação' },
  { codigo:'2320-25', nome:'Diretor Escolar', grupo:'Educação' },
  { codigo:'2320-30', nome:'Pedagogo', grupo:'Educação' },
  { codigo:'2320-35', nome:'Psicopedagogo', grupo:'Educação' },
  { codigo:'2320-40', nome:'Fonoaudiólogo Escolar', grupo:'Educação' },
  { codigo:'2321-10', nome:'Professor de Matemática', grupo:'Educação' },
  { codigo:'2321-15', nome:'Professor de Português', grupo:'Educação' },
  { codigo:'2321-20', nome:'Professor de Inglês', grupo:'Educação' },
  { codigo:'2321-25', nome:'Professor de Educação Física', grupo:'Educação' },
  { codigo:'2321-30', nome:'Professor de Ciências', grupo:'Educação' },
  { codigo:'2321-35', nome:'Professor de Química', grupo:'Educação' },
  { codigo:'2321-40', nome:'Professor de Física', grupo:'Educação' },
  { codigo:'2321-45', nome:'Professor de Biologia', grupo:'Educação' },
  { codigo:'2321-50', nome:'Professor de História', grupo:'Educação' },
  { codigo:'2321-55', nome:'Professor de Geografia', grupo:'Educação' },
  { codigo:'2332-10', nome:'Professor de Educação Infantil', grupo:'Educação' },
  { codigo:'2332-15', nome:'Auxiliar de Educação Infantil', grupo:'Educação' },
  { codigo:'4231-10', nome:'Auxiliar Administrativo Escolar', grupo:'Educação' },

  // ── Arte, Cultura e Entretenimento ───────────────────────────
  { codigo:'2621-05', nome:'Ator', grupo:'Arte e Cultura' },
  { codigo:'2621-10', nome:'Cantor', grupo:'Arte e Cultura' },
  { codigo:'2621-15', nome:'Músico', grupo:'Arte e Cultura' },
  { codigo:'2621-20', nome:'Instrumentista', grupo:'Arte e Cultura' },
  { codigo:'2621-25', nome:'Dançarino', grupo:'Arte e Cultura' },
  { codigo:'2621-30', nome:'Bailarino', grupo:'Arte e Cultura' },
  { codigo:'2622-05', nome:'Produtor Cultural', grupo:'Arte e Cultura' },
  { codigo:'2622-10', nome:'Diretor de Teatro', grupo:'Arte e Cultura' },
  { codigo:'2622-15', nome:'Diretor de Cinema', grupo:'Arte e Cultura' },
  { codigo:'2622-20', nome:'Produtor Musical', grupo:'Arte e Cultura' },
  { codigo:'2623-05', nome:'Artista Plástico', grupo:'Arte e Cultura' },
  { codigo:'2623-10', nome:'Escultor', grupo:'Arte e Cultura' },
  { codigo:'2623-15', nome:'Ilustrador', grupo:'Arte e Cultura' },
  { codigo:'2623-20', nome:'Cenógrafo', grupo:'Arte e Cultura' },
  { codigo:'5191-10', nome:'Técnico de Som', grupo:'Arte e Cultura' },
  { codigo:'5191-15', nome:'Técnico de Iluminação', grupo:'Arte e Cultura' },
  { codigo:'5191-20', nome:'Operador de Câmera', grupo:'Arte e Cultura' },

  // ── Esporte e Lazer ──────────────────────────────────────────
  { codigo:'3711-05', nome:'Atleta Profissional', grupo:'Esporte' },
  { codigo:'3711-10', nome:'Jogador de Futebol', grupo:'Esporte' },
  { codigo:'3712-05', nome:'Treinador de Futebol', grupo:'Esporte' },
  { codigo:'3712-10', nome:'Personal Trainer', grupo:'Esporte' },
  { codigo:'3712-15', nome:'Professor de Educação Física', grupo:'Esporte' },
  { codigo:'3712-20', nome:'Instrutor de Academia', grupo:'Esporte' },
  { codigo:'3712-25', nome:'Árbitro de Futebol', grupo:'Esporte' },
  { codigo:'3712-30', nome:'Preparador Físico', grupo:'Esporte' },
  { codigo:'3712-35', nome:'Fisioterapeuta Esportivo', grupo:'Esporte' },
  { codigo:'3712-40', nome:'Instrutor de Natação', grupo:'Esporte' },
  { codigo:'3712-45', nome:'Instrutor de Artes Marciais', grupo:'Esporte' },
  { codigo:'5193-05', nome:'Recreacionista', grupo:'Esporte' },
  { codigo:'5193-10', nome:'Animador de Eventos', grupo:'Esporte' },

  // ── Setor Público e Forças de Segurança ──────────────────────
  { codigo:'1111-15', nome:'Servidor Público Federal', grupo:'Setor Público' },
  { codigo:'1111-20', nome:'Servidor Público Estadual', grupo:'Setor Público' },
  { codigo:'1111-25', nome:'Servidor Público Municipal', grupo:'Setor Público' },
  { codigo:'5173-30', nome:'Agente de Polícia Civil', grupo:'Setor Público' },
  { codigo:'5173-35', nome:'Policial Militar', grupo:'Setor Público' },
  { codigo:'5173-40', nome:'Oficial de Polícia Militar', grupo:'Setor Público' },
  { codigo:'5173-45', nome:'Guarda Municipal', grupo:'Setor Público' },
  { codigo:'5173-50', nome:'Agente de Trânsito', grupo:'Setor Público' },
  { codigo:'5173-55', nome:'Inspetor Fiscal', grupo:'Setor Público' },
  { codigo:'5174-15', nome:'Bombeiro Militar', grupo:'Setor Público' },
  { codigo:'5174-20', nome:'Oficial Bombeiro', grupo:'Setor Público' },
  { codigo:'5175-05', nome:'Agente Penitenciário', grupo:'Setor Público' },
  { codigo:'5175-10', nome:'Agente Socioeducativo', grupo:'Setor Público' },
  { codigo:'2143-10', nome:'Engenheiro Fiscal', grupo:'Setor Público' },
  { codigo:'2521-15', nome:'Fiscal de Tributos', grupo:'Setor Público' },
  { codigo:'2521-20', nome:'Auditor Fiscal', grupo:'Setor Público' },

  // ── Energia Elétrica e Saneamento ────────────────────────────
  { codigo:'7244-25', nome:'Eletricista de Alta Tensão', grupo:'Energia' },
  { codigo:'7244-30', nome:'Operador de Subestação Elétrica', grupo:'Energia' },
  { codigo:'7244-35', nome:'Técnico em Sistemas de Energia', grupo:'Energia' },
  { codigo:'7244-40', nome:'Técnico em Energias Renováveis', grupo:'Energia' },
  { codigo:'7244-45', nome:'Técnico em Energia Solar', grupo:'Energia' },
  { codigo:'7244-50', nome:'Instalador de Painéis Fotovoltaicos', grupo:'Energia' },
  { codigo:'7244-55', nome:'Operador de Central Elétrica', grupo:'Energia' },
  { codigo:'7126-15', nome:'Técnico em Saneamento', grupo:'Energia' },
  { codigo:'7126-20', nome:'Operador de Estação de Tratamento de Água', grupo:'Energia' },
  { codigo:'7126-25', nome:'Operador de Estação de Tratamento de Esgoto', grupo:'Energia' },

  // ── Serviços Domésticos ──────────────────────────────────────
  { codigo:'5121-15', nome:'Empregado Doméstico', grupo:'Serviços Domésticos' },
  { codigo:'5121-20', nome:'Cozinheiro Doméstico', grupo:'Serviços Domésticos' },
  { codigo:'5121-25', nome:'Babá', grupo:'Serviços Domésticos' },
  { codigo:'5121-30', nome:'Diarista', grupo:'Serviços Domésticos' },
  { codigo:'5121-35', nome:'Caseiro', grupo:'Serviços Domésticos' },
  { codigo:'5121-40', nome:'Jardineiro', grupo:'Serviços Domésticos' },
  { codigo:'5121-45', nome:'Motorista Particular', grupo:'Serviços Domésticos' },

  // ── Construção — mais específico ─────────────────────────────
  { codigo:'7110-20', nome:'Mestre de Obras', grupo:'Construção' },
  { codigo:'7110-25', nome:'Encarregado de Obra', grupo:'Construção' },
  { codigo:'7121-15', nome:'Operador de Concreteira', grupo:'Construção' },
  { codigo:'7125-20', nome:'Marceneiro de Obras', grupo:'Construção' },
  { codigo:'7126-30', nome:'Técnico em Hidráulica Predial', grupo:'Construção' },
  { codigo:'7131-30', nome:'Pintor de Fachada', grupo:'Construção' },
  { codigo:'7141-20', nome:'Assentador de Cerâmica', grupo:'Construção' },
  { codigo:'7150-10', nome:'Encanador Predial', grupo:'Construção' },
  { codigo:'7152-10', nome:'Rigger (Montador de Andaimes)', grupo:'Construção' },
  { codigo:'7155-10', nome:'Operador de Bomba de Concreto', grupo:'Construção' },
  { codigo:'7163-50', nome:'Operador de Munk', grupo:'Construção' },
  { codigo:'7163-55', nome:'Operador de Plataforma Elevatória', grupo:'Construção' },
  { codigo:'7165-10', nome:'Impermeabilizador', grupo:'Construção' },
  { codigo:'7167-15', nome:'Instalador de Forro', grupo:'Construção' },
  { codigo:'7167-20', nome:'Instalador de Divisórias', grupo:'Construção' },
  { codigo:'7168-10', nome:'Instalador de Esquadrias', grupo:'Construção' },
  { codigo:'7169-10', nome:'Técnico em Segurança Predial', grupo:'Construção' },
  { codigo:'3118-10', nome:'Técnico em Topografia', grupo:'Construção' },
  { codigo:'3118-15', nome:'Topógrafo', grupo:'Construção' },
  { codigo:'3118-20', nome:'Desenhista Técnico (Civil)', grupo:'Construção' },
  { codigo:'3118-25', nome:'Projetista de Edificações', grupo:'Construção' },
  { codigo:'3118-30', nome:'Técnico em Geoprocessamento', grupo:'Construção' },

  // ── Engenharia — mais específico ─────────────────────────────
  { codigo:'2141-20', nome:'Engenheiro de Instalações', grupo:'Engenharia' },
  { codigo:'2141-25', nome:'Engenheiro de Fundações', grupo:'Engenharia' },
  { codigo:'2142-10', nome:'Engenheiro de Manutenção Industrial', grupo:'Engenharia' },
  { codigo:'2143-15', nome:'Engenheiro de Energia', grupo:'Engenharia' },
  { codigo:'2143-20', nome:'Engenheiro Eletricista Sênior', grupo:'Engenharia' },
  { codigo:'2144-10', nome:'Engenheiro de Processo', grupo:'Engenharia' },
  { codigo:'2145-10', nome:'Engenheiro de Qualidade', grupo:'Engenharia' },
  { codigo:'2146-10', nome:'Engenheiro de Materiais', grupo:'Engenharia' },
  { codigo:'2149-05', nome:'Engenheiro Biomédico', grupo:'Engenharia' },
  { codigo:'2149-10', nome:'Engenheiro Ambiental Sênior', grupo:'Engenharia' },
  { codigo:'2149-15', nome:'Engenheiro de Segurança do Trabalho Sênior', grupo:'Engenharia' },
  { codigo:'2149-20', nome:'Engenheiro de Projetos', grupo:'Engenharia' },
  { codigo:'2149-25', nome:'Engenheiro Eletrotécnico', grupo:'Engenharia' },
  { codigo:'2149-30', nome:'Engenheiro de Controle e Automação', grupo:'Engenharia' },
  { codigo:'2149-35', nome:'Engenheiro de Telecomunicações', grupo:'Engenharia' },
  { codigo:'2149-40', nome:'Engenheiro Naval', grupo:'Engenharia' },
  { codigo:'2149-45', nome:'Engenheiro Aeronáutico', grupo:'Engenharia' },
  { codigo:'2149-50', nome:'Engenheiro de Petróleo', grupo:'Engenharia' },
  { codigo:'3121-10', nome:'Técnico Mecânico de Manutenção', grupo:'Engenharia' },
  { codigo:'3121-15', nome:'Técnico em Mecatrônica', grupo:'Engenharia' },
  { codigo:'3131-10', nome:'Técnico em Eletrotécnica Industrial', grupo:'Engenharia' },
  { codigo:'3132-20', nome:'Técnico em Eletrônica Industrial', grupo:'Engenharia' },
  { codigo:'3143-10', nome:'Técnico em Análise Química', grupo:'Engenharia' },
  { codigo:'3152-10', nome:'Técnico em Segurança do Trabalho Sênior', grupo:'Engenharia' },

  // ── Agronegócio e Ciências Agrárias ─────────────────────────
  { codigo:'2141-30', nome:'Engenheiro Florestal', grupo:'Agrícola' },
  { codigo:'2141-35', nome:'Engenheiro de Pesca', grupo:'Agrícola' },
  { codigo:'2148-10', nome:'Engenheiro de Alimentos', grupo:'Agrícola' },
  { codigo:'2148-15', nome:'Zootecnista', grupo:'Agrícola' },
  { codigo:'2241-05', nome:'Médico Veterinário', grupo:'Agrícola' },
  { codigo:'2241-10', nome:'Médico Veterinário de Campo', grupo:'Agrícola' },
  { codigo:'3241-05', nome:'Técnico Agropecuário', grupo:'Agrícola' },
  { codigo:'3241-10', nome:'Técnico Florestal', grupo:'Agrícola' },
  { codigo:'3241-15', nome:'Técnico em Aquicultura', grupo:'Agrícola' },
  { codigo:'3241-20', nome:'Auxiliar Veterinário', grupo:'Agrícola' },
  { codigo:'6110-55', nome:'Trabalhador em Fruticultura', grupo:'Agrícola' },
  { codigo:'6110-60', nome:'Irrigador Agrícola', grupo:'Agrícola' },
  { codigo:'6111-25', nome:'Trabalhador em Cunicultura (Coelhos)', grupo:'Agrícola' },
  { codigo:'6112-15', nome:'Lenhador', grupo:'Agrícola' },
  { codigo:'6113-05', nome:'Apicultor', grupo:'Agrícola' },
  { codigo:'6113-10', nome:'Auxiliar Apicultor', grupo:'Agrícola' },
  { codigo:'6220-15', nome:'Aquicultor', grupo:'Pesca' },
  { codigo:'6220-20', nome:'Auxiliar de Aquicultura', grupo:'Pesca' },

  // ── Gestão e Ciências Empresariais ───────────────────────────
  { codigo:'1141-05', nome:'Diretor Jurídico', grupo:'Direção' },
  { codigo:'1141-10', nome:'Diretor de Marketing', grupo:'Direção' },
  { codigo:'1141-15', nome:'Diretor de RH', grupo:'Direção' },
  { codigo:'1141-20', nome:'Diretor de TI', grupo:'Direção' },
  { codigo:'1141-25', nome:'Diretor Administrativo Financeiro (CFO)', grupo:'Direção' },
  { codigo:'1142-05', nome:'Consultor de Gestão', grupo:'Direção' },
  { codigo:'1142-10', nome:'Consultor Empresarial', grupo:'Direção' },
  { codigo:'2521-25', nome:'Administrador de Empresas', grupo:'Administrativo' },
  { codigo:'2521-30', nome:'Analista de Negócios', grupo:'Administrativo' },
  { codigo:'2521-35', nome:'Analista de Processos', grupo:'Administrativo' },
  { codigo:'2521-40', nome:'Analista de Inovação', grupo:'Administrativo' },
  { codigo:'2525-05', nome:'Profissional de Relações Institucionais', grupo:'Administrativo' },
  { codigo:'2525-10', nome:'Analista de Sustentabilidade', grupo:'Administrativo' },

  // ── Pesquisa e Ciências ──────────────────────────────────────
  { codigo:'2111-05', nome:'Físico', grupo:'Ciências' },
  { codigo:'2111-10', nome:'Químico', grupo:'Ciências' },
  { codigo:'2112-05', nome:'Geólogo', grupo:'Ciências' },
  { codigo:'2112-10', nome:'Geofísico', grupo:'Ciências' },
  { codigo:'2113-05', nome:'Meteorologista', grupo:'Ciências' },
  { codigo:'2121-05', nome:'Matemático', grupo:'Ciências' },
  { codigo:'2121-10', nome:'Estatístico', grupo:'Ciências' },
  { codigo:'2122-05', nome:'Astrônomo', grupo:'Ciências' },
  { codigo:'2131-05', nome:'Biólogo', grupo:'Ciências' },
  { codigo:'2131-10', nome:'Ecólogo', grupo:'Ciências' },
  { codigo:'2131-15', nome:'Microbiologista', grupo:'Ciências' },
  { codigo:'2131-20', nome:'Bioquímico', grupo:'Ciências' },
  { codigo:'2131-25', nome:'Geneticista', grupo:'Ciências' },
  { codigo:'2132-05', nome:'Pesquisador', grupo:'Ciências' },
  { codigo:'2132-10', nome:'Analista de Pesquisa e Desenvolvimento (P&D)', grupo:'Ciências' },
  { codigo:'2133-05', nome:'Oceanógrafo', grupo:'Ciências' },
  { codigo:'2133-10', nome:'Hidrólogo', grupo:'Ciências' },

  // ── Assistência Social ───────────────────────────────────────
  { codigo:'2515-05', nome:'Assistente Social', grupo:'Social' },
  { codigo:'2515-10', nome:'Assistente Social Hospitalar', grupo:'Social' },
  { codigo:'2515-15', nome:'Assistente Social Escolar', grupo:'Social' },
  { codigo:'2516-05', nome:'Sociólogo', grupo:'Social' },
  { codigo:'2516-10', nome:'Antropólogo', grupo:'Social' },
  { codigo:'5151-15', nome:'Cuidador Social', grupo:'Social' },
  { codigo:'5152-05', nome:'Agente Social', grupo:'Social' },
  { codigo:'5163-10', nome:'Educador Social', grupo:'Social' },
  { codigo:'5163-15', nome:'Monitor de Abrigo', grupo:'Social' },

  // ── Logística Avançada ───────────────────────────────────────
  { codigo:'1234-10', nome:'Gerente de Supply Chain', grupo:'Logística' },
  { codigo:'2521-45', nome:'Analista de Supply Chain', grupo:'Logística' },
  { codigo:'2521-50', nome:'Analista de Logística', grupo:'Logística' },
  { codigo:'2521-55', nome:'Analista de Transportes', grupo:'Logística' },
  { codigo:'3548-15', nome:'Despachante Aduaneiro', grupo:'Logística' },
  { codigo:'3548-20', nome:'Analista de Comércio Exterior', grupo:'Logística' },
  { codigo:'3548-25', nome:'Assistente de Importação e Exportação', grupo:'Logística' },
  { codigo:'4141-60', nome:'Conferente de Exportação', grupo:'Logística' },
  { codigo:'5191-25', nome:'Manobrista', grupo:'Logística' },
  { codigo:'5153-15', nome:'Operador de Dock', grupo:'Logística' },
  { codigo:'5153-20', nome:'Operador de Reach Stacker', grupo:'Logística' },
  { codigo:'5153-25', nome:'Operador de Transtainer', grupo:'Logística' },

  // ── Produção — mais específico ───────────────────────────────
  { codigo:'8282-05', nome:'Operador de Torno Mecânico', grupo:'Produção' },
  { codigo:'8282-10', nome:'Operador de Fresadora', grupo:'Produção' },
  { codigo:'8282-15', nome:'Operador de Retífica', grupo:'Produção' },
  { codigo:'8282-20', nome:'Operador de Dobradeira', grupo:'Produção' },
  { codigo:'8282-25', nome:'Operador de Corte a Laser', grupo:'Produção' },
  { codigo:'8283-05', nome:'Operador de Solda por Robô', grupo:'Produção' },
  { codigo:'8284-05', nome:'Operador de Estamparia', grupo:'Produção' },
  { codigo:'8285-05', nome:'Operador de Fundição', grupo:'Produção' },
  { codigo:'8285-10', nome:'Moldador de Fundição', grupo:'Produção' },
  { codigo:'8483-05', nome:'Operador de Paletizadora', grupo:'Produção' },
  { codigo:'8483-10', nome:'Operador de Linha de Envase', grupo:'Produção' },
  { codigo:'8483-15', nome:'Operador de Envase Asséptico', grupo:'Produção' },
  { codigo:'8484-05', nome:'Operador de Rotulagem', grupo:'Produção' },
  { codigo:'8485-10', nome:'Auxiliar de Produção Industrial', grupo:'Produção' },
  { codigo:'8485-15', nome:'Conferente de Produção', grupo:'Produção' },
  { codigo:'8485-20', nome:'Inspetor de Produção', grupo:'Produção' },

  // ── Serviços Gerais ──────────────────────────────────────────
  { codigo:'9913-10', nome:'Auxiliar de Serviços Gerais', grupo:'Serviços Gerais' },
  { codigo:'9913-15', nome:'Operador de Máquina de Lavar', grupo:'Serviços Gerais' },
  { codigo:'9913-20', nome:'Lavador de Veículos', grupo:'Serviços Gerais' },
  { codigo:'9913-25', nome:'Lavador e Passador de Roupas', grupo:'Serviços Gerais' },
  { codigo:'9913-30', nome:'Tintureiro', grupo:'Serviços Gerais' },
  { codigo:'9913-35', nome:'Auxiliar de Cozinha Industrial', grupo:'Serviços Gerais' },
  { codigo:'9913-40', nome:'Auxiliar de Padaria Industrial', grupo:'Serviços Gerais' },
  { codigo:'9913-45', nome:'Auxiliar de Buffet', grupo:'Serviços Gerais' },
  { codigo:'9914-05', nome:'Embalador a Mão', grupo:'Serviços Gerais' },
  { codigo:'9914-10', nome:'Sacador de Malha Têxtil', grupo:'Serviços Gerais' },
  { codigo:'9915-05', nome:'Catador de Materiais Recicláveis', grupo:'Serviços Gerais' },
]

export function buscarCBO(termo: string): CBO[] {
  if (!termo || termo.length < 2) return []
  const t = termo.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '')
  return CBO_DATA.filter(c => {
    const nome = c.nome.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    const cod  = c.codigo.replace(/\D/g,'')
    return nome.includes(t) || cod.includes(t)
  }).slice(0, 10)
}

// Retorna o melhor CBO para uma fun\u00e7\u00e3o/cargo \u2014 sempre retorna algo se houver qualquer correspond\u00eancia
export function melhorCBO(funcao: string): CBO | null {
  if (!funcao || funcao.length < 2) return null
  const norm = (s: string) => s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim()
  const t = norm(funcao)
  const palavras = t.split(/\s+/).filter(w => w.length > 3)

  let best: CBO | null = null
  let bestScore = 0

  for (const c of CBO_DATA) {
    const nome = norm(c.nome)
    let score = 0

    if (nome === t)              score = 100  // correspond\u00eancia exata
    else if (nome.startsWith(t)) score = 85   // nome come\u00e7a com o termo
    else if (t.startsWith(nome)) score = 75   // termo come\u00e7a com o nome (nome mais curto)
    else if (nome.includes(t))   score = 65   // nome cont\u00e9m o termo
    else if (t.includes(nome))   score = 55   // termo cont\u00e9m o nome
    else if (palavras.length > 0) {
      // correspond\u00eancia por palavras significativas
      const acertos = palavras.filter(w => nome.includes(w)).length
      if (acertos > 0) score = acertos * 25
    }

    if (score > bestScore) { bestScore = score; best = c }
  }

  return best
}
